import Link from "next/link";
import { db } from "@/lib/db";
import { rupiah } from "@/lib/utils";

export default async function Home() {
  const plans = await db.plan.findMany({ where: { isActive: true }, orderBy: { price: "asc" } });
  return <main>
    <section className="hero"><div className="container hero-grid"><div><div className="eyebrow">✦ Platform pertumbuhan digital terpadu</div><h1>Belajar. Bertumbuh. <em>Berpenghasilan.</em></h1><p className="hero-copy">Satu ekosistem untuk mengakses materi terarah, komunitas membership, dan peluang affiliate yang transparan. Mulai dari langkah kecil, bangun hasil yang berkelanjutan.</p><div className="hero-actions"><Link href="/register" className="btn btn-primary">Mulai Jadi Member →</Link><Link href="#fitur" className="btn btn-ghost">Lihat Cara Kerja</Link></div><div className="trust"><span>✓ Materi terstruktur</span><span>✓ Komisi transparan</span><span>✓ Dukungan komunitas</span></div></div><div className="mock"><div className="mock-inner"><div className="mock-top"><i className="dot"/><i className="dot"/><i className="dot"/></div><div className="dash-sample"><div className="welcome"><b>Selamat datang, Member 👋</b><p>Lanjutkan progres terbaikmu hari ini.</p></div><div className="stat-row"><div className="mini-stat"><small>Progres LMS</small><b>68%</b></div><div className="mini-stat"><small>Referral</small><b>24</b></div><div className="mini-stat"><small>Komisi</small><b>Rp1,2jt</b></div></div><div className="course-line"><div className="course-icon">▶</div><div style={{flex:1}}><b>Fondasi Bisnis Digital</b><div className="progress" style={{marginTop:8}}><span style={{width:"68%"}}/></div></div></div></div></div></div></div></section>
    <section className="section section-white" id="fitur"><div className="container"><div className="section-head"><span className="eyebrow">Semua dalam satu tempat</span><h2>Ekosistem untuk kemajuan nyata</h2><p>Bukan sekadar kumpulan materi. RizqHub menghubungkan proses belajar, komunitas, dan sistem referral dalam perjalanan yang jelas.</p></div><div className="feature-grid"><article className="feature-card"><div className="icon">◫</div><h3>LMS Terstruktur</h3><p>Kursus dibagi menjadi modul dan pelajaran. Pantau progres serta lanjutkan belajar tanpa kehilangan arah.</p></article><article className="feature-card"><div className="icon">♙</div><h3>Membership Eksklusif</h3><p>Akses konten sesuai paket, pembaruan materi, dan manfaat khusus selama masa membership aktif.</p></article><article className="feature-card"><div className="icon">↗</div><h3>Affiliate Transparan</h3><p>Dapatkan tautan referral unik. Pantau klik, referral, serta komisi dari dashboard pribadi.</p></article></div></div></section>
    <section className="section" id="paket"><div className="container"><div className="section-head"><span className="eyebrow">Pilih akses Anda</span><h2>Paket sederhana, manfaat jelas</h2><p>Mulai sesuai kebutuhan. Seluruh pembayaran saat ini diverifikasi manual oleh admin.</p></div><div className="pricing">{plans.map(p=><article key={p.id} className={`price-card ${p.isPopular?"popular":""}`}>{p.isPopular&&<span className="badge">Paling diminati</span>}<h3>{p.name}</h3><p className="muted">{p.description}</p><div className="price">{rupiah(p.price)} <small>/ {p.durationDays >= 3650 ? "akses panjang" : `${p.durationDays} hari`}</small></div><ul className="checks">{(p.features as string[]).map(f=><li key={f}>{f}</li>)}</ul><Link href={`/register?plan=${p.slug}`} className={`btn btn-block ${p.isPopular?"btn-primary":"btn-ghost"}`}>Pilih {p.name}</Link></article>)}</div></div></section>
    <section className="section section-white" id="faq"><div className="container"><div className="section-head"><h2>Pertanyaan yang sering ditanyakan</h2></div><div className="faq"><details><summary>Bagaimana pembayaran dilakukan?</summary><p>Pilih paket, transfer ke rekening yang ditampilkan, lalu kirim bukti pembayaran. Admin akan memverifikasi secara manual dan mengaktifkan membership.</p></details><details><summary>Bagaimana cara kerja affiliate?</summary><p>Setelah mendaftar, Anda memperoleh link referral unik. Komisi tercatat ketika pengguna yang mendaftar melalui link tersebut membeli paket dan pembayarannya disetujui.</p></details><details><summary>Apakah materi LMS langsung terbuka?</summary><p>Materi preview dapat dilihat secara terbatas. Seluruh materi sesuai paket terbuka setelah membership aktif.</p></details></div></div></section>
  </main>;
}
