type LessonInput={id?:string;title:string;content:string;videoUrl:string|null;durationMinutes:number;isPreview:boolean;position:number};
type ModuleInput={id?:string;title:string;position:number;lessons:LessonInput[]};
export type CourseInput={title:string;description:string;thumbnail:string|null;isPublished:boolean;planIds:string[];modules:ModuleInput[];updatedAt:string|null};
export type ValidationResult={ok:true;value:CourseInput}|{ok:false;error:string};
export function validateVideoUrl(value:string){try{const u=new URL(value);if(u.protocol!=="https:")return false;return ["youtube.com","www.youtube.com","www.youtube-nocookie.com"].includes(u.hostname)?/^\/embed\/[A-Za-z0-9_-]+$/.test(u.pathname):u.hostname==="player.vimeo.com"&&/^\/video\/\d+$/.test(u.pathname)}catch{return false}}
export function normalizeCourseInput(raw:unknown):ValidationResult{
 if(!raw||typeof raw!=="object")return{ok:false,error:"Data kursus tidak valid."};const d=raw as Record<string,unknown>,title=String(d.title??"").trim(),description=String(d.description??"").trim();
 if(title.length<3||title.length>150)return{ok:false,error:"Judul harus 3–150 karakter."};if(description.length<10||description.length>5000)return{ok:false,error:"Deskripsi harus 10–5000 karakter."};
 const thumbnail=String(d.thumbnail??"").trim()||null;if(thumbnail&&(!/^https:\/\//.test(thumbnail)||thumbnail.length>2000))return{ok:false,error:"URL thumbnail harus menggunakan HTTPS."};
 if(!Array.isArray(d.planIds)||!d.planIds.every(v=>typeof v==="string"))return{ok:false,error:"Pilihan paket tidak valid."};const planIds=[...new Set(d.planIds.map(v=>v.trim()).filter(Boolean))];
 if(!Array.isArray(d.modules)||d.modules.length>100)return{ok:false,error:"Daftar modul tidak valid."};const moduleIds=new Set<string>(),lessonIds=new Set<string>(),modules:ModuleInput[]=[];
 for(let mi=0;mi<d.modules.length;mi++){const rawMod=d.modules[mi];if(!rawMod||typeof rawMod!=="object")return{ok:false,error:"Data modul tidak valid."};const m=rawMod as Record<string,unknown>,id=typeof m.id==="string"&&m.id?m.id:undefined,mt=String(m.title??"").trim();if(id&&moduleIds.has(id))return{ok:false,error:"ID modul duplikat."};if(id)moduleIds.add(id);if(mt.length<2||mt.length>150)return{ok:false,error:`Judul modul ${mi+1} harus 2–150 karakter.`};if(!Array.isArray(m.lessons)||m.lessons.length>200)return{ok:false,error:`Daftar materi modul ${mi+1} tidak valid.`};const lessons:LessonInput[]=[];
  for(let li=0;li<m.lessons.length;li++){const rawLesson=m.lessons[li];if(!rawLesson||typeof rawLesson!=="object")return{ok:false,error:"Data materi tidak valid."};const l=rawLesson as Record<string,unknown>,lid=typeof l.id==="string"&&l.id?l.id:undefined,lt=String(l.title??"").trim(),content=String(l.content??"").trim(),videoUrl=String(l.videoUrl??"").trim()||null,durationMinutes=Number(l.durationMinutes);if(lid&&lessonIds.has(lid))return{ok:false,error:"ID materi duplikat."};if(lid)lessonIds.add(lid);if(lt.length<2||lt.length>150)return{ok:false,error:`Judul materi ${li+1} harus 2–150 karakter.`};if(!content||content.length>30000)return{ok:false,error:`Isi materi ${li+1} wajib diisi (maks. 30.000 karakter).`};if(!Number.isInteger(durationMinutes)||durationMinutes<1||durationMinutes>1440)return{ok:false,error:`Durasi materi ${li+1} harus 1–1440 menit.`};if(videoUrl&&!validateVideoUrl(videoUrl))return{ok:false,error:`URL video materi ${li+1} harus berupa embed HTTPS YouTube atau Vimeo.`};lessons.push({id:lid,title:lt,content,videoUrl,durationMinutes,isPreview:l.isPreview===true,position:li+1})}
  modules.push({id,title:mt,position:mi+1,lessons});}
 const updatedAt=typeof d.updatedAt==="string"&&d.updatedAt?d.updatedAt:null;if(updatedAt&&Number.isNaN(Date.parse(updatedAt)))return{ok:false,error:"Versi kursus tidak valid."};
 return{ok:true,value:{title,description,thumbnail,isPublished:d.isPublished===true,planIds,modules,updatedAt}};
}
